name: Build Stages

permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  
  build:
    runs-on: ubuntu-latest

    container:
      image: 'debian:stable'
    
    steps:
      
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies...
        run: |
          apt-get update
          apt-get upgrade -y
          apt-get clean
          apt-get install git python3 python3-pip pkg-config build-essential -y

      - name: OS Release
        run: |
          cat /etc/os-release

      - name: Installing Meson and Ninja build system
        run: |
          python3 -m pip install meson ninja --break-system-packages
          meson --version
          ninja --version

      - name: Build Default
        run: |
          meson setup --native-file config.ini build
          meson compile -C build

      - name: Run tests with Default optimization
        run: |
          meson test --print-errorlogs -C build
          rm -rf build
      
      - name: Build debug
        run: |
          meson setup build --native-file config.ini --buildtype=debug
          meson compile -C build

      - name: Run tests in Debug
        run: |
          meson test --print-errorlogs -C build
          rm -rf build

      - name: Build release
        run: |
          meson setup --native-file config.ini build --buildtype=release
          meson compile -C build

      - name: Run tests in Debug
        run: |
          meson test --print-errorlogs -C build
          rm -rf build

