name: Build Stages

permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  
  build:
    runs-on: ubuntu-latest

    container:
      image: 'debian:stable'
    
    steps:
      
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies...
        run: |
          apt-get update
          apt-get upgrade -y
          apt-get clean
          apt-get install git python3 python3-pip pkg-config gcc build-essential valgrind -y

      - name: OS Release
        run: |
          cat /etc/os-release

      - name: Installing Meson and Ninja build system
        run: |
          python3 -m pip install meson ninja --break-system-packages
          meson --version
          ninja --version

      - name: Build Default
        run: |
          meson setup build
          meson compile -C build
          rm -rf build

      - name: Build custom
        run: |
          meson setup build --buildtype=custom
          meson compile -C build
          rm -rf build
      
      - name: Build debug
        run: |
          meson setup build --buildtype=debug
          meson compile -C build
          rm -rf build

      - name: Build release
        run: |
          meson setup build --buildtype=release
          meson compile -C build
          rm -rf build

      - name: Build Project
        run: |
          meson setup build --buildtype=debug
          meson compile -C build

      - name: Run tests
        run: |
          meson test --print-errorlogs -C build

      - name: Run tests with Valgrind
        run: |
          valgrind --version
          meson test -C build --wrap='valgrind --leak-check=full --track-fds=yes --trace-children=yes'

