name: Norminette

permissions:
  contents: read

on:
  push:
    branches: ["main"]
  pull_requests:
    branches: ["main"]

jobs:
  
  norm:
    
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies on Debian ...
        run: |
          cat /etc/os-release
          apt-get update
          apt-get upgrade -y
          apt-get install git python3 python3-pip python3-venv pkg-config cmake gcc build-essential clang-tidy clang-format -y
          apt-get clean

      - name: Installing Meson
        run: |
          python3 -m pip install meson --break-system-packages
          meson --version

      - name: Installing Ninja
        run: |
          python3 -m pip install ninja --break-system-packages
          ninja --version

      - name: Norm Sources files
        run: |
          meson setup build
          clang-tidy -p ./build/compile_commands.json --config-file=$PWD/.clang-tidy --quiet $(find ./inc/ -name "*.h" 2>/dev/null)
          clang-tidy -p ./build/compile_commands.json --config-file=$PWD/.clang-tidy --quiet $(find ./src/ -name "*.c" 2>/dev/null)

      - name: Format code
        continue-on-error: true
        run: |
          ls -la
          clang-format -style="file" -i $(find ./inc/ -name "*.h" 2>/dev/null)
          clang-format -style="file" -i $(find ./src/ -name "*.c" 2>/dev/null)
          git config --global --add safe.directory $PWD
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -a -m "Add changes format"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.ref }}
