name: Unit Tests

permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  
  tests:
    
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies...
        run: |
          cat /etc/os-release
          apt-get update
          apt-get upgrade -y
          apt-get clean
          apt-get install git python3 python3-pip python3-venv pkg-config zsh cmake gcc clang build-essential valgrind libc-devtools heaptrack -y

      - name: Installing Meson
        run: |
          python3 -m pip install meson --break-system-packages
          meson --version

      - name: Installing Ninja
        run: |
          python3 -m pip install ninja --break-system-packages
          ninja --version

      - name: Build Project
        run: |
          meson setup build --buildtype=debug
          meson compile -C build

      - name: Run tests
        run: |
          meson test --print-errorlogs -C build

      - name: Run tests with Memusage
        run: |
          memusage --version
          meson test -C build --wrap='memusage -m'

      - name: Run tests with Valgrind
        run: |
          valgrind --version
          meson test -C build --wrap='valgrind --leak-check=full --track-fds=yes --trace-children=yes'


      - name: Run tests with Hellgrind
        run: |
          valgrind --version
          meson test -C build --wrap='valgrind --tool=helgrind'

